runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /httpbin/static
  static_dir: static
- url: /httpbin/templates
  static_dir: static  
- url: /httpbin/.*
  script: httpbin.app

libraries:
- name: flask
  version: 0.12