apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-12-03T12:29:49Z
  generation: 2
  labels:
    app: app-bin-test
  name: app-bin-test
  namespace: default
  resourceVersion: "15839"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/app-bin-test
  uid: 2072bc32-f6f7-11e8-9f86-42010a800146
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-bin-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-bin-test
    spec:
      containers:
      - image: gcr.io/osc-http-bin/liaison-http-bin:latest
        imagePullPolicy: Always
        name: liaison-http-bin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-12-03T12:29:52Z
    lastUpdateTime: 2018-12-03T12:29:52Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
