apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-12-03T12:30:26Z
  labels:
    app: app-bin-test
  name: app-bin-test-service
  namespace: default
  resourceVersion: "15846"
  selfLink: /api/v1/namespaces/default/services/app-bin-test-service
  uid: 362f6300-f6f7-11e8-9f86-42010a800146
spec:
  clusterIP: 10.39.245.38
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30625
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: app-bin-test
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.226.159.205